# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mbKIfhCmtlddbfYEd4DLLQrUkJ4w1aa3
"""

aku = list(input())
print(aku)
aku.append("buku")
print(aku)
aku.remove("b")
print(aku)
aku[2] = "pulpen"
print(aku)